Code taken from the README file, adapted to use weighted network

In [5]:
import numpy as np
import pandas as pd

src = '../data/raw_networks' # root dir of data
meta = pd.read_csv('../data/network_list.csv')
roles = pd.read_csv('../data/node_role.csv')

def loadGame(game, is_weighted):
    # N is the number of players in the game
    # load csv data
    # unweighted and weighted networks can be loaded exactly the same way
    # below shows the loader for weighted networks
    
    if is_weighted:
        df_network = pd.read_csv(f"{src}/network{game}_weighted.csv", index_col=0)
    else:
        df_network = pd.read_csv(f"{src}/network{game}.csv", index_col=0)
    # for dense repr
    #df_network = pd.read_csv(f"{src}/network{game}_weighted.csv", index_col=0)
    
    # get meta NUMBER_OF_PARTICIPANTS by game NETWORK id
    N = meta.loc[game, "NUMBER_OF_PARTICIPANTS"]

    # T is number of timestamps (10 frames)
    T = len(df_network)
    # load VFOA network to T x N x (N+1) array
    # vfoa[t, n, i] is the probability of player n+1 looking at object i at time t
    # i: 0 - laptop, 1 - player 1, 2 - player 2, ..., N - player N
    vfoa = np.reshape(df_network.values, (T, N, N + 1))

    # print information
    print(f"network id:{game}\t length(x 1/3 second): {T}\t num of players: {N}")
    return vfoa

In [10]:
for _, meta_row in meta.iterrows():
    game_id = meta_row['NETWORK']
    if len(roles[roles['ID'] == game_id]) == 0:
        print(f"No roles for game {game_id}")
        continue
        
    #game = loadGame(game_id, 0)
    game_weighted = loadGame(game_id, 1)
    
    records = []

    #t, n1, n2 = game.shape
    t, n1, n2 = game_weighted.shape

    # this is 0-indexed while nodes are 1-indexed
    game_roles = {i: roles[
                (roles["node"] == f"P{i+1}") & (roles["ID"] == game_id)
            ]["role"].values[0] for i in range(n1)}

    records = []
    for timestep, frame in enumerate(game_weighted):
        #print(f"timestep {timestep} {frame}")

        # get max index of each row 
        max_index = np.argmax(frame, axis=1)
        for i, item_id in enumerate(max_index):
            # get the role of user i in game game_id
            role = game_roles[i]
            list_of_features = frame[i].tolist()

            # record: user_id, item_id, timestamp, state_label,  feature
            records.append([i + 1, item_id, timestep, role] + list_of_features)

    
    game_df = pd.DataFrame(records)
    game_df.columns = ["user_id", "item_id", "timestamp", "state_label"] + [f"feature {i}" for i in range(len(game_df.columns) - 4)]
    game_df.to_csv(f"../data/processed_networks/network_{game_id}.csv", index=False, header=False)

network id:0	 length(x 1/3 second): 7323	 num of players: 7
No roles for game 1
network id:2	 length(x 1/3 second): 7533	 num of players: 7
network id:3	 length(x 1/3 second): 6264	 num of players: 7
network id:4	 length(x 1/3 second): 7323	 num of players: 8
network id:5	 length(x 1/3 second): 9651	 num of players: 8
network id:6	 length(x 1/3 second): 7260	 num of players: 7
network id:7	 length(x 1/3 second): 7245	 num of players: 6
network id:8	 length(x 1/3 second): 6243	 num of players: 7
No roles for game 9
network id:10	 length(x 1/3 second): 6681	 num of players: 7
network id:11	 length(x 1/3 second): 5415	 num of players: 7
network id:12	 length(x 1/3 second): 5571	 num of players: 8
network id:13	 length(x 1/3 second): 7173	 num of players: 7
network id:14	 length(x 1/3 second): 9429	 num of players: 8
network id:15	 length(x 1/3 second): 5466	 num of players: 6
network id:16	 length(x 1/3 second): 6678	 num of players: 6
network id:17	 length(x 1/3 second): 3054	 num of pla

Flatten the adjacency matrix so that each row represents the gaze vector of the user.
Convert this into the wikipedia format and save as CSV

In [4]:
import os

# create `network_processed` directory if it doesn't exist
if not os.path.exists("network_weighted_processed"):
    os.makedirs("network_weighted_processed")

In [12]:
game = loadGame(0, 1)
for timestep, frame in enumerate(game):
        print(f"timestep {timestep} {frame}")

network id:0	 length(x 1/3 second): 7323	 num of players: 7
timestep 0 [[0.534 0.    0.046 0.083 0.    0.041 0.029 0.067]
 [0.077 0.023 0.    0.127 0.011 0.025 0.034 0.503]
 [0.079 0.03  0.041 0.    0.039 0.041 0.037 0.533]
 [0.1   0.049 0.019 0.063 0.    0.073 0.377 0.12 ]
 [0.043 0.034 0.04  0.357 0.02  0.    0.05  0.256]
 [0.15  0.111 0.131 0.128 0.044 0.115 0.    0.12 ]
 [0.094 0.071 0.136 0.172 0.053 0.165 0.109 0.   ]]
timestep 1 [[0.646 0.    0.061 0.123 0.    0.05  0.029 0.091]
 [0.086 0.021 0.    0.164 0.014 0.043 0.043 0.629]
 [0.169 0.037 0.047 0.    0.057 0.053 0.043 0.594]
 [0.014 0.056 0.013 0.039 0.    0.07  0.653 0.156]
 [0.029 0.043 0.057 0.443 0.029 0.    0.054 0.346]
 [0.116 0.08  0.414 0.151 0.034 0.085 0.    0.12 ]
 [0.017 0.05  0.45  0.178 0.051 0.182 0.071 0.   ]]
timestep 2 [[0.73  0.    0.043 0.088 0.006 0.041 0.021 0.071]
 [0.086 0.014 0.    0.173 0.014 0.041 0.043 0.629]
 [0.109 0.037 0.056 0.    0.067 0.06  0.041 0.63 ]
 [0.014 0.057 0.014 0.043 0.    0.071 

timestep 340 [[0.017 0.    0.114 0.152 0.007 0.127 0.054 0.529]
 [0.    0.    0.    0.646 0.049 0.039 0.009 0.257]
 [0.03  0.041 0.054 0.    0.461 0.157 0.11  0.146]
 [0.414 0.06  0.036 0.084 0.    0.079 0.134 0.193]
 [0.159 0.084 0.109 0.18  0.017 0.    0.027 0.424]
 [0.096 0.041 0.049 0.063 0.    0.068 0.    0.683]
 [0.021 0.044 0.114 0.144 0.054 0.21  0.411 0.   ]]
timestep 341 [[0.024 0.    0.114 0.156 0.004 0.128 0.044 0.529]
 [0.    0.    0.    0.669 0.037 0.047 0.009 0.239]
 [0.    0.027 0.034 0.    0.609 0.127 0.083 0.12 ]
 [0.514 0.053 0.033 0.104 0.    0.094 0.043 0.159]
 [0.131 0.083 0.117 0.209 0.034 0.    0.026 0.4  ]
 [0.093 0.043 0.053 0.07  0.    0.064 0.    0.677]
 [0.077 0.034 0.09  0.12  0.05  0.107 0.521 0.   ]]
timestep 342 [[0.03  0.    0.113 0.145 0.006 0.128 0.05  0.529]
 [0.036 0.01  0.    0.474 0.031 0.125 0.043 0.281]
 [0.    0.027 0.043 0.    0.609 0.131 0.083 0.107]
 [0.474 0.05  0.03  0.104 0.    0.104 0.07  0.167]
 [0.091 0.066 0.113 0.261 0.026 0.    0.0

 [0.013 0.683 0.057 0.11  0.014 0.108 0.014 0.   ]]
timestep 645 [[0.017 0.    0.111 0.16  0.01  0.115 0.063 0.524]
 [0.081 0.014 0.    0.177 0.027 0.034 0.03  0.636]
 [0.046 0.244 0.263 0.    0.063 0.207 0.051 0.126]
 [0.497 0.063 0.051 0.073 0.    0.084 0.093 0.139]
 [0.024 0.084 0.106 0.327 0.036 0.    0.02  0.403]
 [0.001 0.031 0.026 0.72  0.034 0.003 0.    0.184]
 [0.006 0.699 0.053 0.089 0.014 0.123 0.017 0.   ]]
timestep 646 [[0.029 0.    0.111 0.163 0.016 0.117 0.039 0.526]
 [0.027 0.01  0.    0.294 0.056 0.142 0.167 0.304]
 [0.011 0.033 0.043 0.    0.564 0.161 0.114 0.073]
 [0.53  0.074 0.039 0.09  0.    0.087 0.106 0.074]
 [0.037 0.079 0.093 0.341 0.046 0.    0.023 0.381]
 [0.003 0.031 0.029 0.797 0.043 0.    0.    0.097]
 [0.016 0.267 0.207 0.318 0.03  0.128 0.034 0.   ]]
timestep 647 [[0.054 0.    0.107 0.195 0.027 0.126 0.041 0.449]
 [0.004 0.    0.    0.309 0.047 0.291 0.039 0.31 ]
 [0.    0.031 0.041 0.    0.614 0.163 0.101 0.049]
 [0.199 0.064 0.023 0.069 0.    0.094 0.

timestep 936 [[0.019 0.    0.106 0.135 0.001 0.078 0.036 0.626]
 [0.096 0.017 0.    0.04  0.003 0.014 0.02  0.81 ]
 [0.054 0.084 0.051 0.    0.177 0.141 0.113 0.379]
 [0.261 0.044 0.036 0.08  0.    0.077 0.204 0.297]
 [0.03  0.089 0.1   0.043 0.016 0.    0.037 0.686]
 [0.031 0.024 0.054 0.056 0.011 0.034 0.    0.789]
 [0.03  0.014 0.071 0.057 0.029 0.057 0.741 0.   ]]
timestep 937 [[0.026 0.    0.106 0.151 0.    0.088 0.054 0.576]
 [0.127 0.009 0.    0.047 0.003 0.023 0.019 0.773]
 [0.037 0.041 0.047 0.    0.226 0.22  0.089 0.34 ]
 [0.051 0.043 0.033 0.308 0.    0.161 0.024 0.38 ]
 [0.033 0.091 0.1   0.043 0.016 0.    0.04  0.677]
 [0.046 0.08  0.08  0.101 0.029 0.056 0.    0.609]
 [0.031 0.014 0.071 0.057 0.029 0.057 0.74  0.   ]]
timestep 938 [[0.    0.    0.01  0.006 0.    0.    0.003 0.981]
 [0.1   0.    0.    0.    0.    0.    0.    0.9  ]
 [0.039 0.013 0.033 0.    0.034 0.576 0.034 0.271]
 [0.043 0.06  0.037 0.076 0.    0.091 0.026 0.667]
 [0.019 0.049 0.086 0.023 0.013 0.    0.0

timestep 1276 [[0.001 0.    0.013 0.009 0.    0.001 0.001 0.974]
 [0.033 0.673 0.    0.013 0.    0.009 0.    0.273]
 [0.    0.    0.01  0.    0.    0.    0.    0.99 ]
 [0.566 0.037 0.043 0.014 0.    0.057 0.043 0.24 ]
 [0.009 0.019 0.033 0.01  0.007 0.    0.033 0.89 ]
 [0.    0.    0.007 0.    0.    0.    0.    0.993]
 [0.014 0.683 0.056 0.1   0.    0.11  0.037 0.   ]]
timestep 1277 [[0.014 0.    0.106 0.148 0.    0.115 0.041 0.576]
 [0.1   0.31  0.    0.122 0.009 0.037 0.011 0.411]
 [0.481 0.043 0.034 0.    0.043 0.061 0.016 0.321]
 [0.567 0.044 0.046 0.03  0.    0.057 0.063 0.193]
 [0.016 0.039 0.033 0.309 0.029 0.    0.146 0.43 ]
 [0.079 0.033 0.066 0.084 0.003 0.064 0.    0.671]
 [0.014 0.567 0.08  0.155 0.004 0.139 0.04  0.   ]]
timestep 1278 [[0.014 0.    0.116 0.169 0.016 0.124 0.033 0.529]
 [0.044 0.18  0.    0.466 0.056 0.094 0.004 0.156]
 [0.46  0.037 0.039 0.    0.063 0.077 0.036 0.289]
 [0.59  0.047 0.056 0.043 0.    0.071 0.121 0.071]
 [0.014 0.029 0.04  0.551 0.034 0.    

timestep 1479 [[0.014 0.    0.174 0.374 0.    0.253 0.    0.184]
 [0.629 0.029 0.    0.157 0.029 0.036 0.029 0.093]
 [0.054 0.079 0.06  0.    0.053 0.691 0.04  0.023]
 [0.    0.043 0.003 0.797 0.    0.087 0.013 0.057]
 [0.056 0.126 0.146 0.31  0.031 0.    0.019 0.313]
 [0.071 0.007 0.043 0.139 0.    0.09  0.    0.65 ]
 [0.009 0.079 0.206 0.547 0.026 0.116 0.019 0.   ]]
timestep 1480 [[0.081 0.    0.15  0.349 0.001 0.228 0.004 0.186]
 [0.629 0.029 0.    0.157 0.029 0.037 0.029 0.091]
 [0.061 0.087 0.071 0.    0.064 0.604 0.073 0.039]
 [0.    0.043 0.    0.786 0.    0.1   0.014 0.057]
 [0.066 0.126 0.154 0.166 0.031 0.    0.031 0.426]
 [0.064 0.104 0.063 0.123 0.003 0.084 0.    0.559]
 [0.001 0.046 0.474 0.362 0.011 0.095 0.01  0.   ]]
timestep 1481 [[0.016 0.    0.15  0.361 0.    0.235 0.004 0.234]
 [0.629 0.029 0.    0.15  0.029 0.044 0.029 0.091]
 [0.046 0.034 0.024 0.    0.06  0.746 0.06  0.03 ]
 [0.004 0.043 0.    0.787 0.    0.098 0.014 0.053]
 [0.069 0.121 0.137 0.144 0.034 0.    

 [0.014 0.021 0.066 0.119 0.04  0.151 0.589 0.   ]]
timestep 1787 [[0.026 0.    0.099 0.534 0.02  0.159 0.034 0.129]
 [0.    0.    0.    0.264 0.044 0.149 0.014 0.529]
 [0.    0.029 0.026 0.    0.621 0.153 0.114 0.057]
 [0.34  0.056 0.016 0.268 0.    0.164 0.104 0.053]
 [0.057 0.043 0.069 0.544 0.053 0.    0.016 0.219]
 [0.014 0.026 0.014 0.233 0.589 0.077 0.    0.047]
 [0.    0.014 0.064 0.103 0.043 0.061 0.714 0.   ]]
timestep 1788 [[0.006 0.    0.081 0.749 0.017 0.034 0.024 0.089]
 [0.003 0.    0.    0.478 0.05  0.127 0.014 0.329]
 [0.    0.029 0.014 0.    0.629 0.157 0.114 0.057]
 [0.361 0.04  0.014 0.295 0.    0.133 0.11  0.047]
 [0.003 0.009 0.01  0.784 0.12  0.    0.01  0.064]
 [0.014 0.019 0.    0.266 0.567 0.088 0.    0.046]
 [0.009 0.014 0.054 0.119 0.046 0.054 0.704 0.   ]]
timestep 1789 [[0.    0.    0.071 0.816 0.016 0.003 0.014 0.08 ]
 [0.003 0.    0.    0.67  0.08  0.14  0.014 0.093]
 [0.    0.029 0.02  0.    0.629 0.157 0.109 0.057]
 [0.371 0.043 0.014 0.286 0.    0.128

timestep 2060 [[0.05  0.    0.09  0.262 0.029 0.092 0.04  0.437]
 [0.    0.    0.    0.832 0.097 0.053 0.014 0.003]
 [0.023 0.044 0.034 0.    0.501 0.19  0.134 0.073]
 [0.024 0.031 0.031 0.666 0.    0.203 0.013 0.031]
 [0.044 0.006 0.003 0.836 0.004 0.    0.019 0.089]
 [0.014 0.029 0.03  0.231 0.574 0.087 0.    0.036]
 [0.027 0.044 0.091 0.17  0.069 0.174 0.424 0.   ]]
timestep 2061 [[0.023 0.    0.07  0.665 0.026 0.088 0.039 0.09 ]
 [0.    0.    0.    0.887 0.057 0.042 0.004 0.01 ]
 [0.021 0.044 0.029 0.    0.496 0.214 0.136 0.06 ]
 [0.023 0.007 0.014 0.85  0.    0.081 0.013 0.011]
 [0.003 0.    0.    0.911 0.    0.    0.014 0.071]
 [0.004 0.013 0.011 0.767 0.147 0.023 0.    0.034]
 [0.029 0.057 0.089 0.37  0.074 0.177 0.204 0.   ]]
timestep 2062 [[0.01  0.    0.054 0.782 0.024 0.04  0.024 0.066]
 [0.006 0.    0.    0.749 0.043 0.068 0.    0.134]
 [0.036 0.059 0.277 0.    0.054 0.077 0.054 0.443]
 [0.001 0.004 0.023 0.907 0.    0.043 0.009 0.013]
 [0.    0.    0.    0.954 0.    0.    

timestep 2311 [[0.03  0.    0.61  0.17  0.014 0.067 0.034 0.074]
 [0.001 0.003 0.    0.764 0.071 0.101 0.014 0.046]
 [0.047 0.289 0.309 0.    0.067 0.126 0.07  0.093]
 [0.014 0.057 0.014 0.123 0.    0.073 0.607 0.111]
 [0.004 0.023 0.054 0.71  0.039 0.    0.02  0.15 ]
 [0.014 0.024 0.033 0.36  0.467 0.057 0.    0.044]
 [0.029 0.051 0.103 0.334 0.053 0.112 0.319 0.   ]]
timestep 2312 [[0.013 0.    0.276 0.548 0.013 0.075 0.019 0.057]
 [0.    0.011 0.    0.793 0.08  0.094 0.017 0.004]
 [0.001 0.016 0.007 0.    0.629 0.163 0.121 0.063]
 [0.061 0.059 0.023 0.22  0.    0.133 0.409 0.096]
 [0.027 0.04  0.143 0.606 0.064 0.    0.021 0.099]
 [0.014 0.029 0.027 0.198 0.624 0.068 0.    0.04 ]
 [0.133 0.04  0.131 0.238 0.044 0.12  0.293 0.   ]]
timestep 2313 [[0.    0.    0.071 0.784 0.014 0.053 0.014 0.063]
 [0.001 0.029 0.    0.761 0.076 0.109 0.014 0.01 ]
 [0.    0.024 0.014 0.    0.644 0.146 0.107 0.064]
 [0.514 0.043 0.033 0.186 0.    0.128 0.061 0.034]
 [0.031 0.034 0.086 0.464 0.034 0.    

timestep 2676 [[0.013 0.    0.134 0.554 0.027 0.135 0.053 0.084]
 [0.    0.    0.    0.796 0.061 0.107 0.013 0.023]
 [0.037 0.326 0.41  0.    0.026 0.121 0.039 0.041]
 [0.017 0.031 0.034 0.836 0.    0.06  0.001 0.02 ]
 [0.004 0.01  0.004 0.971 0.001 0.    0.    0.009]
 [0.013 0.024 0.007 0.351 0.507 0.075 0.    0.023]
 [0.066 0.054 0.111 0.426 0.157 0.151 0.034 0.   ]]
timestep 2677 [[0.01  0.    0.064 0.781 0.017 0.052 0.017 0.059]
 [0.    0.    0.    0.929 0.029 0.036 0.007 0.   ]
 [0.053 0.171 0.523 0.    0.053 0.104 0.041 0.054]
 [0.    0.004 0.017 0.92  0.    0.034 0.006 0.019]
 [0.    0.    0.    1.    0.    0.    0.    0.   ]
 [0.014 0.029 0.016 0.312 0.537 0.072 0.    0.02 ]
 [0.081 0.027 0.069 0.559 0.107 0.117 0.04  0.   ]]
timestep 2678 [[0.    0.    0.05  0.801 0.021 0.046 0.017 0.064]
 [0.    0.    0.    0.917 0.033 0.037 0.01  0.003]
 [0.02  0.029 0.029 0.    0.524 0.216 0.127 0.056]
 [0.004 0.011 0.    0.897 0.    0.048 0.014 0.024]
 [0.013 0.02  0.029 0.889 0.031 0.    

 [0.027 0.027 0.124 0.09  0.031 0.147 0.553 0.   ]]
timestep 3003 [[0.011 0.    0.116 0.557 0.016 0.147 0.051 0.101]
 [0.037 0.651 0.    0.056 0.011 0.024 0.014 0.206]
 [0.581 0.063 0.061 0.    0.074 0.1   0.049 0.071]
 [0.581 0.05  0.046 0.095 0.    0.131 0.053 0.044]
 [0.057 0.079 0.079 0.166 0.03  0.    0.029 0.561]
 [0.121 0.1   0.224 0.235 0.031 0.147 0.    0.141]
 [0.08  0.054 0.107 0.528 0.039 0.078 0.114 0.   ]]
timestep 3004 [[0.    0.    0.073 0.725 0.016 0.072 0.019 0.096]
 [0.027 0.789 0.    0.073 0.    0.014 0.014 0.083]
 [0.637 0.057 0.044 0.    0.061 0.097 0.043 0.06 ]
 [0.576 0.029 0.043 0.17  0.    0.111 0.057 0.014]
 [0.057 0.071 0.057 0.286 0.029 0.    0.029 0.471]
 [0.027 0.031 0.059 0.711 0.029 0.046 0.    0.097]
 [0.    0.071 0.077 0.735 0.027 0.051 0.039 0.   ]]
timestep 3005 [[0.    0.    0.073 0.759 0.014 0.089 0.014 0.05 ]
 [0.039 0.68  0.    0.083 0.    0.011 0.029 0.159]
 [0.643 0.057 0.043 0.    0.057 0.1   0.043 0.057]
 [0.573 0.027 0.043 0.182 0.    0.104

timestep 3235 [[0.167 0.    0.089 0.448 0.02  0.113 0.027 0.136]
 [0.169 0.041 0.    0.148 0.021 0.03  0.043 0.547]
 [0.01  0.029 0.064 0.    0.107 0.057 0.06  0.673]
 [0.014 0.043 0.01  0.724 0.    0.076 0.011 0.121]
 [0.056 0.071 0.057 0.286 0.016 0.    0.043 0.471]
 [0.241 0.08  0.136 0.299 0.017 0.099 0.    0.127]
 [0.056 0.06  0.08  0.633 0.046 0.103 0.023 0.   ]]
timestep 3236 [[0.004 0.    0.147 0.566 0.014 0.084 0.019 0.166]
 [0.264 0.026 0.    0.145 0.016 0.04  0.04  0.469]
 [0.031 0.013 0.071 0.    0.08  0.377 0.047 0.38 ]
 [0.017 0.036 0.011 0.73  0.    0.073 0.01  0.123]
 [0.051 0.071 0.057 0.286 0.02  0.    0.043 0.471]
 [0.15  0.031 0.096 0.168 0.001 0.084 0.    0.47 ]
 [0.001 0.057 0.074 0.721 0.05  0.082 0.014 0.   ]]
timestep 3237 [[0.006 0.    0.18  0.629 0.021 0.078 0.026 0.06 ]
 [0.076 0.003 0.    0.456 0.071 0.204 0.041 0.149]
 [0.033 0.    0.064 0.    0.057 0.723 0.041 0.081]
 [0.007 0.029 0.004 0.825 0.    0.083 0.014 0.039]
 [0.043 0.071 0.057 0.286 0.029 0.    

timestep 3514 [[0.    0.    0.067 0.667 0.011 0.083 0.016 0.156]
 [0.071 0.077 0.    0.143 0.014 0.041 0.029 0.624]
 [0.044 0.046 0.726 0.    0.014 0.066 0.014 0.09 ]
 [0.013 0.279 0.024 0.076 0.    0.108 0.054 0.446]
 [0.    0.039 0.077 0.627 0.039 0.    0.01  0.209]
 [0.089 0.067 0.116 0.15  0.006 0.175 0.    0.397]
 [0.029 0.23  0.357 0.24  0.017 0.104 0.023 0.   ]]
timestep 3515 [[0.196 0.    0.066 0.379 0.009 0.083 0.024 0.243]
 [0.076 0.066 0.    0.142 0.014 0.041 0.029 0.633]
 [0.047 0.033 0.649 0.    0.014 0.044 0.014 0.199]
 [0.026 0.054 0.014 0.061 0.    0.086 0.09  0.669]
 [0.    0.036 0.066 0.614 0.033 0.    0.01  0.241]
 [0.093 0.047 0.107 0.119 0.009 0.103 0.    0.523]
 [0.017 0.143 0.111 0.578 0.019 0.109 0.023 0.   ]]
timestep 3516 [[0.197 0.    0.037 0.063 0.    0.042 0.029 0.631]
 [0.027 0.021 0.    0.058 0.004 0.018 0.011 0.86 ]
 [0.029 0.029 0.586 0.    0.014 0.043 0.014 0.286]
 [0.02  0.017 0.004 0.016 0.    0.037 0.04  0.866]
 [0.007 0.023 0.026 0.197 0.007 0.    

 [0.019 0.037 0.103 0.132 0.049 0.121 0.54  0.   ]]
timestep 3768 [[0.123 0.    0.114 0.271 0.    0.129 0.074 0.289]
 [0.004 0.    0.    0.688 0.026 0.09  0.02  0.171]
 [0.03  0.04  0.077 0.    0.359 0.176 0.187 0.131]
 [0.603 0.051 0.036 0.04  0.    0.089 0.086 0.096]
 [0.026 0.053 0.274 0.094 0.02  0.    0.227 0.306]
 [0.084 0.043 0.06  0.082 0.006 0.074 0.    0.651]
 [0.046 0.051 0.116 0.239 0.046 0.118 0.384 0.   ]]
timestep 3769 [[0.036 0.    0.12  0.187 0.001 0.126 0.051 0.479]
 [0.01  0.    0.    0.621 0.026 0.083 0.016 0.244]
 [0.043 0.057 0.087 0.    0.243 0.19  0.234 0.146]
 [0.593 0.037 0.029 0.049 0.    0.079 0.077 0.137]
 [0.021 0.049 0.036 0.114 0.031 0.    0.529 0.22 ]
 [0.087 0.036 0.056 0.093 0.001 0.058 0.    0.669]
 [0.033 0.039 0.096 0.152 0.014 0.449 0.217 0.   ]]
timestep 3770 [[0.034 0.    0.116 0.147 0.    0.126 0.051 0.526]
 [0.009 0.    0.    0.709 0.037 0.133 0.023 0.089]
 [0.037 0.047 0.084 0.    0.213 0.157 0.206 0.256]
 [0.619 0.051 0.03  0.04  0.    0.097

timestep 4003 [[0.114 0.    0.036 0.299 0.    0.014 0.013 0.524]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.037 0.    0.    0.    0.013 0.01  0.    0.94 ]
 [0.001 0.    0.    0.003 0.    0.02  0.001 0.974]
 [0.    0.019 0.011 0.089 0.    0.    0.51  0.371]
 [0.001 0.    0.019 0.007 0.    0.003 0.    0.97 ]
 [0.019 0.049 0.073 0.472 0.049 0.088 0.251 0.   ]]
timestep 4004 [[0.001 0.    0.009 0.013 0.    0.006 0.007 0.964]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.001 0.    0.    0.    0.    0.    0.    0.999]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.023 0.014 0.036 0.    0.    0.529 0.399]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.029 0.05  0.073 0.346 0.04  0.072 0.39  0.   ]]
timestep 4005 [[0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.021 0.014 0.03  0.    0.    

timestep 4247 [[0.39  0.    0.079 0.063 0.    0.017 0.009 0.443]
 [0.    0.    0.    0.467 0.014 0.093 0.    0.426]
 [0.013 0.043 0.217 0.    0.027 0.046 0.023 0.631]
 [0.006 0.02  0.011 0.019 0.    0.053 0.021 0.87 ]
 [0.026 0.053 0.054 0.031 0.017 0.    0.076 0.743]
 [0.001 0.    0.027 0.001 0.004 0.006 0.    0.96 ]
 [0.024 0.023 0.077 0.131 0.009 0.346 0.39  0.   ]]
timestep 4248 [[0.129 0.    0.007 0.021 0.    0.    0.001 0.841]
 [0.    0.    0.    0.503 0.014 0.073 0.    0.41 ]
 [0.007 0.037 0.194 0.    0.024 0.036 0.02  0.681]
 [0.    0.    0.    0.    0.    0.004 0.    0.996]
 [0.009 0.01  0.021 0.001 0.004 0.    0.023 0.931]
 [0.001 0.004 0.011 0.01  0.001 0.003 0.    0.969]
 [0.023 0.044 0.086 0.184 0.001 0.597 0.064 0.   ]]
timestep 4249 [[0.32  0.    0.014 0.03  0.    0.006 0.003 0.627]
 [0.    0.    0.    0.52  0.014 0.056 0.    0.41 ]
 [0.017 0.04  0.269 0.    0.026 0.034 0.02  0.594]
 [0.019 0.037 0.007 0.037 0.    0.056 0.044 0.8  ]
 [0.033 0.061 0.049 0.164 0.016 0.    

 [0.034 0.073 0.084 0.455 0.017 0.278 0.059 0.   ]]
timestep 4416 [[0.011 0.    0.06  0.162 0.001 0.068 0.029 0.669]
 [0.254 0.007 0.    0.027 0.007 0.026 0.007 0.671]
 [0.    0.017 0.029 0.    0.5   0.101 0.05  0.303]
 [0.043 0.033 0.026 0.04  0.    0.056 0.051 0.751]
 [0.024 0.054 0.07  0.034 0.021 0.    0.016 0.78 ]
 [0.033 0.017 0.061 0.047 0.    0.028 0.    0.813]
 [0.044 0.089 0.296 0.252 0.004 0.241 0.074 0.   ]]
timestep 4417 [[0.    0.    0.014 0.214 0.    0.023 0.    0.749]
 [0.006 0.    0.    0.014 0.    0.    0.    0.98 ]
 [0.003 0.031 0.031 0.    0.481 0.116 0.037 0.3  ]
 [0.023 0.021 0.007 0.01  0.    0.007 0.006 0.926]
 [0.006 0.017 0.037 0.006 0.011 0.    0.006 0.917]
 [0.    0.    0.    0.    0.003 0.    0.    0.997]
 [0.009 0.037 0.604 0.217 0.007 0.103 0.023 0.   ]]
timestep 4418 [[0.    0.    0.026 0.074 0.    0.046 0.001 0.853]
 [0.023 0.009 0.    0.037 0.    0.008 0.006 0.917]
 [0.    0.017 0.029 0.    0.503 0.1   0.061 0.29 ]
 [0.017 0.011 0.001 0.017 0.    0.04 

timestep 4532 [[0.01  0.    0.079 0.654 0.021 0.105 0.026 0.106]
 [0.021 0.043 0.    0.104 0.014 0.038 0.714 0.066]
 [0.    0.029 0.023 0.    0.62  0.156 0.121 0.051]
 [0.097 0.081 0.064 0.353 0.    0.242 0.067 0.096]
 [0.046 0.027 0.04  0.691 0.037 0.    0.006 0.153]
 [0.03  0.03  0.147 0.561 0.04  0.049 0.    0.143]
 [0.049 0.039 0.38  0.23  0.06  0.112 0.13  0.   ]]
timestep 4533 [[0.01  0.    0.106 0.558 0.013 0.102 0.047 0.164]
 [0.014 0.043 0.    0.115 0.016 0.041 0.707 0.064]
 [0.    0.029 0.027 0.    0.626 0.143 0.119 0.057]
 [0.383 0.071 0.049 0.17  0.    0.154 0.124 0.049]
 [0.051 0.039 0.07  0.451 0.033 0.    0.021 0.334]
 [0.073 0.034 0.381 0.128 0.036 0.051 0.    0.297]
 [0.044 0.03  0.491 0.205 0.047 0.09  0.093 0.   ]]
timestep 4534 [[0.026 0.    0.114 0.316 0.014 0.151 0.073 0.306]
 [0.014 0.043 0.    0.129 0.019 0.041 0.693 0.061]
 [0.    0.029 0.029 0.    0.629 0.143 0.114 0.057]
 [0.371 0.08  0.04  0.119 0.    0.126 0.196 0.069]
 [0.043 0.054 0.101 0.35  0.027 0.    

timestep 4629 [[0.194 0.    0.126 0.267 0.011 0.122 0.061 0.219]
 [0.106 0.073 0.    0.145 0.017 0.045 0.017 0.597]
 [0.073 0.05  0.084 0.    0.156 0.161 0.133 0.343]
 [0.03  0.07  0.023 0.743 0.    0.083 0.013 0.039]
 [0.62  0.046 0.036 0.171 0.037 0.    0.014 0.076]
 [0.011 0.029 0.036 0.438 0.393 0.04  0.    0.054]
 [0.    0.699 0.049 0.089 0.011 0.121 0.031 0.   ]]
timestep 4630 [[0.043 0.    0.116 0.2   0.019 0.093 0.043 0.487]
 [0.134 0.304 0.    0.165 0.019 0.042 0.019 0.317]
 [0.047 0.029 0.079 0.    0.114 0.189 0.061 0.481]
 [0.02  0.057 0.03  0.792 0.    0.084 0.001 0.016]
 [0.353 0.023 0.019 0.551 0.017 0.    0.01  0.027]
 [0.02  0.021 0.136 0.695 0.026 0.017 0.    0.086]
 [0.    0.699 0.056 0.092 0.014 0.111 0.029 0.   ]]
timestep 4631 [[0.047 0.    0.08  0.231 0.014 0.073 0.016 0.539]
 [0.329 0.011 0.    0.453 0.029 0.086 0.029 0.064]
 [0.034 0.007 0.047 0.    0.039 0.52  0.039 0.314]
 [0.011 0.054 0.027 0.799 0.    0.08  0.007 0.021]
 [0.    0.011 0.    0.989 0.    0.    

 [0.01  0.539 0.117 0.15  0.009 0.148 0.029 0.   ]]
timestep 4891 [[0.    0.    0.029 0.484 0.    0.    0.    0.487]
 [0.089 0.014 0.    0.162 0.014 0.027 0.043 0.651]
 [0.037 0.026 0.044 0.    0.069 0.057 0.061 0.706]
 [0.567 0.043 0.041 0.029 0.    0.043 0.051 0.226]
 [0.06  0.043 0.051 0.353 0.049 0.    0.014 0.43 ]
 [0.086 0.043 0.073 0.084 0.    0.057 0.    0.657]
 [0.001 0.7   0.057 0.102 0.014 0.097 0.029 0.   ]]
timestep 4892 [[0.01  0.    0.056 0.244 0.    0.027 0.029 0.634]
 [0.049 0.011 0.    0.101 0.004 0.022 0.03  0.783]
 [0.027 0.02  0.056 0.    0.079 0.04  0.05  0.729]
 [0.211 0.041 0.027 0.033 0.    0.024 0.357 0.306]
 [0.047 0.014 0.029 0.177 0.029 0.    0.023 0.681]
 [0.069 0.043 0.069 0.071 0.    0.049 0.    0.7  ]
 [0.013 0.607 0.086 0.132 0.004 0.125 0.033 0.   ]]
timestep 4893 [[0.014 0.    0.061 0.124 0.    0.046 0.043 0.711]
 [0.007 0.    0.    0.01  0.    0.    0.013 0.97 ]
 [0.021 0.029 0.051 0.    0.034 0.017 0.029 0.819]
 [0.049 0.043 0.02  0.029 0.    0.029

 [0.014 0.023 0.049 0.182 0.047 0.075 0.61  0.   ]]
timestep 5060 [[0.003 0.    0.149 0.687 0.016 0.052 0.02  0.074]
 [0.    0.    0.    0.878 0.046 0.054 0.014 0.007]
 [0.096 0.044 0.069 0.    0.32  0.213 0.2   0.059]
 [0.063 0.06  0.026 0.124 0.    0.054 0.249 0.424]
 [0.011 0.009 0.014 0.841 0.023 0.    0.017 0.084]
 [0.014 0.017 0.001 0.278 0.55  0.095 0.    0.044]
 [0.001 0.017 0.05  0.129 0.043 0.073 0.687 0.   ]]
timestep 5061 [[0.266 0.    0.113 0.352 0.014 0.106 0.046 0.103]
 [0.    0.    0.    0.872 0.05  0.053 0.014 0.01 ]
 [0.03  0.031 0.036 0.    0.507 0.193 0.146 0.057]
 [0.029 0.064 0.014 0.059 0.    0.054 0.627 0.153]
 [0.027 0.017 0.033 0.75  0.03  0.    0.017 0.126]
 [0.009 0.021 0.019 0.433 0.406 0.054 0.    0.059]
 [0.01  0.031 0.071 0.106 0.046 0.098 0.637 0.   ]]
timestep 5062 [[0.109 0.    0.147 0.472 0.014 0.144 0.016 0.099]
 [0.    0.    0.    0.89  0.037 0.05  0.014 0.009]
 [0.    0.029 0.014 0.    0.571 0.2   0.134 0.051]
 [0.081 0.053 0.01  0.103 0.    0.044

timestep 5191 [[0.031 0.    0.161 0.3   0.01  0.146 0.073 0.279]
 [0.094 0.027 0.    0.147 0.006 0.051 0.044 0.63 ]
 [0.054 0.087 0.691 0.    0.016 0.073 0.017 0.061]
 [0.053 0.07  0.031 0.083 0.    0.091 0.226 0.446]
 [0.104 0.043 0.063 0.459 0.024 0.    0.019 0.289]
 [0.07  0.041 0.719 0.076 0.041 0.014 0.    0.039]
 [0.007 0.033 0.079 0.119 0.044 0.067 0.651 0.   ]]
timestep 5192 [[0.02  0.    0.136 0.206 0.007 0.115 0.054 0.461]
 [0.093 0.037 0.    0.14  0.009 0.048 0.044 0.629]
 [0.06  0.103 0.559 0.    0.04  0.096 0.031 0.111]
 [0.049 0.069 0.024 0.059 0.    0.064 0.437 0.299]
 [0.651 0.056 0.046 0.05  0.046 0.    0.016 0.136]
 [0.066 0.04  0.694 0.067 0.043 0.    0.    0.09 ]
 [0.017 0.03  0.06  0.117 0.043 0.052 0.681 0.   ]]
timestep 5193 [[0.026 0.    0.103 0.165 0.014 0.109 0.05  0.533]
 [0.06  0.009 0.    0.533 0.049 0.136 0.087 0.127]
 [0.087 0.159 0.314 0.    0.089 0.203 0.08  0.069]
 [0.004 0.469 0.031 0.067 0.    0.107 0.043 0.279]
 [0.629 0.049 0.037 0.146 0.039 0.    

 [0.024 0.45  0.081 0.282 0.014 0.121 0.027 0.   ]]
timestep 5363 [[0.024 0.    0.093 0.431 0.001 0.209 0.016 0.226]
 [0.091 0.047 0.    0.14  0.041 0.056 0.569 0.056]
 [0.2   0.076 0.273 0.    0.123 0.176 0.059 0.094]
 [0.593 0.047 0.034 0.105 0.    0.135 0.071 0.014]
 [0.389 0.041 0.044 0.259 0.04  0.    0.02  0.207]
 [0.073 0.04  0.264 0.44  0.033 0.038 0.    0.111]
 [0.026 0.02  0.137 0.123 0.029 0.106 0.56  0.   ]]
timestep 5364 [[0.014 0.    0.054 0.457 0.    0.195 0.014 0.264]
 [0.067 0.05  0.    0.129 0.043 0.063 0.606 0.043]
 [0.117 0.05  0.061 0.    0.096 0.081 0.529 0.066]
 [0.594 0.053 0.046 0.068 0.    0.148 0.06  0.031]
 [0.663 0.053 0.043 0.057 0.043 0.    0.013 0.129]
 [0.166 0.057 0.16  0.275 0.046 0.116 0.    0.18 ]
 [0.034 0.023 0.076 0.107 0.03  0.148 0.583 0.   ]]
timestep 5365 [[0.014 0.    0.053 0.442 0.    0.181 0.03  0.28 ]
 [0.04  0.049 0.    0.127 0.043 0.066 0.629 0.047]
 [0.064 0.043 0.036 0.    0.1   0.061 0.639 0.057]
 [0.577 0.056 0.049 0.055 0.    0.132

 [0.03  0.041 0.044 0.29  0.04  0.147 0.407 0.   ]]
timestep 5566 [[0.369 0.    0.081 0.315 0.016 0.102 0.041 0.076]
 [0.006 0.    0.    0.847 0.027 0.079 0.014 0.027]
 [0.054 0.057 0.134 0.    0.043 0.663 0.021 0.027]
 [0.084 0.029 0.031 0.552 0.    0.245 0.043 0.016]
 [0.426 0.02  0.023 0.456 0.023 0.    0.014 0.039]
 [0.016 0.014 0.051 0.707 0.034 0.043 0.    0.134]
 [0.026 0.044 0.053 0.199 0.033 0.207 0.439 0.   ]]
timestep 5567 [[0.679 0.    0.023 0.152 0.014 0.041 0.017 0.074]
 [0.001 0.    0.    0.867 0.019 0.074 0.014 0.024]
 [0.061 0.096 0.239 0.    0.059 0.457 0.046 0.043]
 [0.033 0.031 0.017 0.746 0.    0.14  0.019 0.014]
 [0.226 0.051 0.049 0.371 0.024 0.    0.027 0.251]
 [0.006 0.017 0.033 0.771 0.026 0.022 0.    0.126]
 [0.029 0.037 0.05  0.277 0.031 0.214 0.361 0.   ]]
timestep 5568 [[0.374 0.    0.074 0.296 0.017 0.067 0.037 0.134]
 [0.007 0.    0.    0.87  0.017 0.072 0.011 0.023]
 [0.04  0.031 0.046 0.    0.379 0.307 0.13  0.067]
 [0.014 0.04  0.006 0.798 0.    0.079

timestep 5722 [[0.01  0.    0.09  0.572 0.01  0.155 0.02  0.143]
 [0.001 0.    0.    0.869 0.017 0.069 0.013 0.03 ]
 [0.106 0.066 0.086 0.    0.216 0.246 0.206 0.076]
 [0.24  0.049 0.034 0.163 0.    0.051 0.131 0.331]
 [0.067 0.016 0.021 0.843 0.02  0.    0.006 0.027]
 [0.    0.016 0.017 0.884 0.033 0.001 0.    0.049]
 [0.    0.226 0.05  0.633 0.014 0.065 0.013 0.   ]]
timestep 5723 [[0.009 0.    0.103 0.442 0.007 0.172 0.009 0.259]
 [0.007 0.    0.    0.837 0.029 0.082 0.014 0.031]
 [0.081 0.051 0.29  0.    0.196 0.174 0.139 0.069]
 [0.033 0.051 0.014 0.084 0.    0.051 0.161 0.604]
 [0.    0.003 0.    0.949 0.    0.    0.007 0.041]
 [0.    0.024 0.024 0.833 0.037 0.001 0.    0.08 ]
 [0.001 0.683 0.039 0.126 0.014 0.113 0.024 0.   ]]
timestep 5724 [[0.029 0.    0.116 0.459 0.023 0.228 0.031 0.114]
 [0.013 0.    0.    0.824 0.026 0.083 0.014 0.04 ]
 [0.071 0.049 0.06  0.    0.409 0.204 0.15  0.057]
 [0.029 0.043 0.056 0.251 0.    0.234 0.053 0.334]
 [0.    0.007 0.    0.987 0.    0.    

timestep 6012 [[0.007 0.    0.233 0.549 0.014 0.092 0.03  0.074]
 [0.03  0.043 0.    0.147 0.03  0.043 0.624 0.083]
 [0.054 0.056 0.717 0.    0.016 0.086 0.014 0.057]
 [0.    0.717 0.079 0.06  0.    0.104 0.014 0.026]
 [0.086 0.119 0.15  0.346 0.08  0.    0.03  0.19 ]
 [0.066 0.047 0.066 0.262 0.036 0.075 0.    0.449]
 [0.003 0.054 0.076 0.512 0.04  0.083 0.231 0.   ]]
timestep 6013 [[0.001 0.    0.15  0.635 0.017 0.125 0.02  0.051]
 [0.004 0.    0.    0.526 0.039 0.34  0.057 0.034]
 [0.043 0.044 0.724 0.    0.014 0.103 0.014 0.057]
 [0.    0.729 0.01  0.077 0.    0.114 0.041 0.029]
 [0.089 0.113 0.111 0.487 0.053 0.    0.029 0.119]
 [0.076 0.049 0.081 0.246 0.006 0.139 0.    0.403]
 [0.    0.057 0.077 0.753 0.029 0.07  0.014 0.   ]]
timestep 6014 [[0.011 0.    0.239 0.471 0.019 0.161 0.029 0.071]
 [0.001 0.    0.    0.544 0.03  0.33  0.057 0.037]
 [0.043 0.043 0.731 0.    0.014 0.097 0.014 0.057]
 [0.    0.724 0.01  0.089 0.    0.106 0.043 0.029]
 [0.094 0.247 0.119 0.349 0.056 0.    

timestep 6291 [[0.    0.    0.061 0.79  0.014 0.05  0.014 0.07 ]
 [0.01  0.    0.    0.848 0.026 0.072 0.014 0.03 ]
 [0.009 0.03  0.033 0.    0.529 0.143 0.114 0.143]
 [0.014 0.547 0.023 0.105 0.    0.093 0.046 0.173]
 [0.011 0.193 0.044 0.553 0.159 0.    0.006 0.034]
 [0.014 0.029 0.029 0.243 0.57  0.075 0.    0.04 ]
 [0.039 0.046 0.084 0.212 0.046 0.232 0.341 0.   ]]
timestep 6292 [[0.011 0.    0.059 0.805 0.02  0.044 0.014 0.047]
 [0.    0.007 0.    0.858 0.039 0.066 0.014 0.016]
 [0.004 0.029 0.036 0.    0.563 0.161 0.107 0.1  ]
 [0.009 0.693 0.031 0.109 0.    0.086 0.043 0.03 ]
 [0.014 0.023 0.007 0.649 0.234 0.    0.003 0.07 ]
 [0.014 0.026 0.01  0.251 0.566 0.081 0.    0.053]
 [0.023 0.013 0.187 0.15  0.061 0.046 0.52  0.   ]]
timestep 6293 [[0.006 0.    0.059 0.69  0.083 0.05  0.019 0.094]
 [0.    0.006 0.    0.822 0.089 0.06  0.013 0.01 ]
 [0.    0.033 0.036 0.    0.611 0.173 0.104 0.043]
 [0.013 0.707 0.047 0.074 0.    0.099 0.031 0.029]
 [0.044 0.034 0.016 0.43  0.444 0.    

timestep 6414 [[0.003 0.    0.11  0.626 0.019 0.086 0.041 0.116]
 [0.064 0.017 0.    0.376 0.039 0.298 0.121 0.084]
 [0.02  0.03  0.057 0.    0.371 0.25  0.167 0.104]
 [0.024 0.05  0.019 0.064 0.    0.06  0.299 0.484]
 [0.029 0.036 0.021 0.241 0.61  0.    0.009 0.054]
 [0.031 0.029 0.061 0.534 0.036 0.065 0.    0.244]
 [0.    0.671 0.043 0.102 0.014 0.141 0.029 0.   ]]
timestep 6415 [[0.004 0.    0.084 0.722 0.014 0.071 0.021 0.083]
 [0.109 0.02  0.    0.395 0.066 0.178 0.129 0.104]
 [0.061 0.041 0.107 0.    0.224 0.337 0.093 0.136]
 [0.076 0.07  0.031 0.124 0.    0.091 0.236 0.371]
 [0.024 0.076 0.139 0.453 0.25  0.    0.016 0.043]
 [0.01  0.024 0.049 0.738 0.037 0.04  0.    0.101]
 [0.    0.67  0.043 0.112 0.014 0.133 0.029 0.   ]]
timestep 6416 [[0.001 0.    0.071 0.761 0.016 0.06  0.017 0.073]
 [0.09  0.02  0.    0.413 0.066 0.188 0.119 0.104]
 [0.02  0.033 0.086 0.    0.491 0.296 0.044 0.03 ]
 [0.096 0.069 0.05  0.44  0.    0.218 0.046 0.081]
 [0.084 0.06  0.07  0.316 0.023 0.    

 [0.05  0.073 0.153 0.241 0.036 0.234 0.213 0.   ]]
timestep 6583 [[0.009 0.    0.114 0.419 0.    0.19  0.013 0.256]
 [0.314 0.011 0.    0.168 0.    0.065 0.084 0.357]
 [0.061 0.08  0.34  0.    0.114 0.111 0.07  0.223]
 [0.593 0.053 0.046 0.085 0.    0.14  0.06  0.024]
 [0.393 0.053 0.057 0.139 0.033 0.    0.016 0.31 ]
 [0.084 0.087 0.387 0.15  0.033 0.062 0.    0.196]
 [0.109 0.084 0.107 0.447 0.046 0.123 0.084 0.   ]]
timestep 6584 [[0.013 0.    0.067 0.448 0.    0.188 0.    0.284]
 [0.24  0.    0.    0.164 0.001 0.038 0.053 0.504]
 [0.046 0.06  0.61  0.    0.077 0.096 0.031 0.08 ]
 [0.583 0.043 0.03  0.123 0.    0.134 0.066 0.021]
 [0.044 0.043 0.057 0.55  0.04  0.    0.026 0.24 ]
 [0.02  0.063 0.046 0.681 0.056 0.029 0.    0.106]
 [0.041 0.051 0.117 0.233 0.079 0.172 0.307 0.   ]]
timestep 6585 [[0.013 0.    0.09  0.411 0.    0.184 0.    0.301]
 [0.2   0.    0.    0.173 0.009 0.033 0.057 0.529]
 [0.046 0.067 0.426 0.    0.071 0.09  0.049 0.251]
 [0.583 0.054 0.041 0.095 0.    0.141

timestep 6746 [[0.014 0.    0.104 0.434 0.    0.158 0.    0.29 ]
 [0.169 0.006 0.    0.182 0.014 0.036 0.043 0.551]
 [0.11  0.027 0.083 0.    0.074 0.44  0.086 0.18 ]
 [0.514 0.046 0.029 0.041 0.    0.064 0.251 0.054]
 [0.017 0.02  0.02  0.48  0.027 0.    0.207 0.229]
 [0.01  0.037 0.047 0.729 0.036 0.026 0.    0.114]
 [0.04  0.063 0.111 0.354 0.104 0.212 0.116 0.   ]]
timestep 6747 [[0.003 0.    0.103 0.375 0.    0.168 0.013 0.339]
 [0.167 0.    0.    0.18  0.014 0.038 0.057 0.543]
 [0.037 0.059 0.209 0.    0.059 0.07  0.059 0.509]
 [0.266 0.076 0.026 0.059 0.    0.07  0.356 0.149]
 [0.054 0.08  0.086 0.194 0.036 0.    0.183 0.367]
 [0.093 0.06  0.344 0.229 0.04  0.092 0.    0.141]
 [0.28  0.074 0.093 0.256 0.031 0.206 0.06  0.   ]]
timestep 6748 [[0.    0.    0.074 0.32  0.    0.116 0.01  0.48 ]
 [0.16  0.    0.    0.17  0.013 0.041 0.053 0.563]
 [0.043 0.537 0.147 0.    0.017 0.073 0.01  0.173]
 [0.033 0.084 0.013 0.069 0.    0.073 0.136 0.593]
 [0.059 0.08  0.13  0.056 0.023 0.    

 [0.001 0.671 0.044 0.104 0.001 0.136 0.041 0.   ]]
timestep 7051 [[0.227 0.    0.114 0.245 0.    0.138 0.061 0.214]
 [0.317 0.239 0.    0.137 0.014 0.023 0.067 0.203]
 [0.064 0.071 0.134 0.    0.267 0.26  0.109 0.094]
 [0.144 0.089 0.076 0.252 0.    0.195 0.13  0.114]
 [0.051 0.074 0.114 0.27  0.046 0.    0.023 0.421]
 [0.091 0.037 0.316 0.171 0.024 0.08  0.    0.28 ]
 [0.    0.671 0.046 0.113 0.007 0.127 0.036 0.   ]]
timestep 7052 [[0.019 0.    0.107 0.239 0.006 0.119 0.054 0.456]
 [0.176 0.107 0.    0.262 0.027 0.236 0.056 0.136]
 [0.07  0.1   0.137 0.    0.259 0.201 0.141 0.091]
 [0.124 0.086 0.074 0.316 0.    0.219 0.073 0.107]
 [0.016 0.047 0.611 0.136 0.023 0.    0.023 0.144]
 [0.08  0.04  0.399 0.178 0.04  0.064 0.    0.199]
 [0.    0.671 0.043 0.116 0.009 0.127 0.034 0.   ]]
timestep 7053 [[0.003 0.    0.099 0.565 0.016 0.131 0.059 0.129]
 [0.011 0.    0.    0.501 0.089 0.293 0.031 0.074]
 [0.066 0.087 0.13  0.    0.307 0.203 0.13  0.077]
 [0.103 0.081 0.067 0.334 0.    0.217

 [0.019 0.081 0.093 0.571 0.063 0.145 0.029 0.   ]]
timestep 7200 [[0.014 0.    0.096 0.55  0.027 0.112 0.05  0.15 ]
 [0.053 0.011 0.    0.534 0.046 0.262 0.051 0.043]
 [0.044 0.029 0.04  0.    0.086 0.057 0.057 0.687]
 [0.511 0.036 0.043 0.188 0.    0.161 0.047 0.014]
 [0.524 0.029 0.029 0.333 0.029 0.    0.014 0.043]
 [0.357 0.053 0.08  0.26  0.027 0.136 0.    0.087]
 [0.    0.043 0.063 0.724 0.049 0.093 0.029 0.   ]]
timestep 7201 [[0.031 0.    0.106 0.304 0.029 0.126 0.047 0.357]
 [0.    0.001 0.    0.642 0.036 0.247 0.037 0.037]
 [0.034 0.029 0.043 0.    0.094 0.057 0.057 0.686]
 [0.557 0.034 0.043 0.153 0.    0.148 0.05  0.014]
 [0.529 0.029 0.029 0.329 0.029 0.    0.014 0.043]
 [0.193 0.073 0.093 0.347 0.029 0.158 0.    0.109]
 [0.    0.043 0.063 0.725 0.051 0.093 0.024 0.   ]]
timestep 7202 [[0.029 0.    0.139 0.425 0.029 0.154 0.056 0.17 ]
 [0.    0.    0.    0.648 0.021 0.169 0.034 0.127]
 [0.023 0.029 0.044 0.    0.1   0.057 0.06  0.687]
 [0.263 0.041 0.033 0.313 0.    0.245